<?php

namespace App\Console\Commands;

use App\Domain\Catalog\Models\Product;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

class ReplicateAgnesColorTempsCommand extends Command
{
    protected $signature = 'products:replicate-agnes-color-temps
        {--dry-run : Do not persist changes}';

    protected $description = 'One-time replication: clone every "Agnes 4000k" product into 3000K (D3) and 2700K (D2) variants, copying specs, packaging, costing, attributes and company links with transformed codes';

    private const SOURCE_FAMILY = 'Agnes 4000k';

    /**
     * @var array<int, array{family: string, model_suffix: string, kelvin: string, supplier_suffix: string}>
     */
    private const TARGETS = [
        ['family' => 'Agnes 3000k', 'model_suffix' => 'D3', 'kelvin' => '3000', 'supplier_suffix' => '3K'],
        ['family' => 'Agnes 2700k', 'model_suffix' => 'D2', 'kelvin' => '2700', 'supplier_suffix' => '27K'],
    ];

    public function handle(): int
    {
        $isDryRun = (bool) $this->option('dry-run');

        $sources = Product::query()
            ->where('product_family', self::SOURCE_FAMILY)
            ->with(['specification', 'packaging', 'costing', 'tags', 'attributeValues', 'companies'])
            ->orderBy('id')
            ->get();

        if ($sources->isEmpty()) {
            $this->warn('No products found with product_family "'.self::SOURCE_FAMILY.'".');

            return self::SUCCESS;
        }

        $created = 0;
        $skipped = 0;

        foreach ($sources as $source) {
            foreach (self::TARGETS as $target) {
                $newModel = $this->transformModelNumber($source->model_number, $target);
                $newRef = $this->transformReferenceCode($source->reference_code, $target);
                $newName = $this->transformKelvinText($source->name, $target);

                if ($this->replicaExists($newModel, $newRef)) {
                    $this->line(sprintf('SKIP  %s → %s (already exists)', $source->model_number, $newModel));
                    $skipped++;

                    continue;
                }

                $this->line(sprintf(
                    '%s%s → %s | %s | ref %s',
                    $isDryRun ? '[DRY RUN] ' : '',
                    $source->model_number,
                    $newModel,
                    $newName,
                    $newRef ?? '—',
                ));

                if (! $isDryRun) {
                    DB::transaction(fn () => $this->replicateProduct($source, $target, $newModel, $newRef, $newName));
                }

                $created++;
            }
        }

        $this->info(sprintf(
            '%s%d product(s) created, %d skipped (already exist), from %d source(s).',
            $isDryRun ? '[DRY RUN] ' : '',
            $created,
            $skipped,
            $sources->count(),
        ));

        return self::SUCCESS;
    }

    private function replicaExists(?string $newModel, ?string $newRef): bool
    {
        if ($newModel === null && $newRef === null) {
            return false;
        }

        return Product::query()
            ->where(function ($q) use ($newModel, $newRef) {
                if ($newModel !== null) {
                    $q->where('model_number', $newModel);
                }
                if ($newRef !== null) {
                    $q->orWhere('reference_code', $newRef);
                }
            })
            ->exists();
    }

    /**
     * @param  array{family: string, model_suffix: string, kelvin: string, supplier_suffix: string}  $target
     */
    private function replicateProduct(Product $source, array $target, ?string $newModel, ?string $newRef, string $newName): void
    {
        $replica = $source->replicate(['sku', 'reference_code']);
        $replica->name = $newName;
        $replica->model_number = $newModel;
        $replica->reference_code = $newRef;
        $replica->product_family = $target['family'];
        $replica->sku = null; // regenerated by the Product creating hook
        $replica->save();

        if ($source->specification) {
            $replica->specification()->create($source->specification->replicate(['id', 'product_id'])->toArray());
        }

        if ($source->packaging) {
            $replica->packaging()->create($source->packaging->replicate(['id', 'product_id'])->toArray());
        }

        if ($source->costing) {
            $replica->costing()->create($source->costing->replicate(['id', 'product_id'])->toArray());
        }

        if ($source->tags->isNotEmpty()) {
            $replica->tags()->sync($source->tags->pluck('id'));
        }

        foreach ($source->attributeValues as $attrValue) {
            $replica->attributeValues()->create([
                'category_attribute_id' => $attrValue->category_attribute_id,
                // Atributo CCT guarda a temperatura de cor como "4000" puro.
                'value' => trim((string) $attrValue->value) === '4000' ? $target['kelvin'] : $attrValue->value,
            ]);
        }

        foreach ($source->companies as $company) {
            $pivotData = collect($company->pivot->toArray())
                ->except(['product_id', 'company_id', 'created_at', 'updated_at'])
                ->toArray();

            $pivotData['external_code'] = $this->transformExternalCode($pivotData['external_code'] ?? null, $target);
            $pivotData['external_name'] = $this->transformKelvinTextNullable($pivotData['external_name'] ?? null, $target);
            $pivotData['external_description'] = $this->transformKelvinTextNullable($pivotData['external_description'] ?? null, $target);

            $replica->companies()->attach($company->id, $pivotData);
        }
    }

    /**
     * AGN7040-D4 → AGN7040-D3 / AGN7040-D2
     *
     * @param  array{model_suffix: string}  $target
     */
    private function transformModelNumber(?string $model, array $target): ?string
    {
        return $model === null ? null : preg_replace('/-D4$/', '-'.$target['model_suffix'], $model);
    }

    /**
     * AGN-40D4 → AGN-40D3 / AGN-40D2
     *
     * @param  array{model_suffix: string}  $target
     */
    private function transformReferenceCode(?string $ref, array $target): ?string
    {
        return $ref === null ? null : preg_replace('/D4$/', $target['model_suffix'], $ref);
    }

    /**
     * "Agnes-40W - 4000K" → "Agnes-40W - 3000K"; trata também "4000k" minúsculo.
     *
     * @param  array{kelvin: string}  $target
     */
    private function transformKelvinText(string $text, array $target): string
    {
        return str_replace(['4000K', '4000k'], [$target['kelvin'].'K', $target['kelvin'].'k'], $text);
    }

    /**
     * @param  array{kelvin: string}  $target
     */
    private function transformKelvinTextNullable(?string $text, array $target): ?string
    {
        return $text === null ? null : $this->transformKelvinText($text, $target);
    }

    /**
     * Códigos externos codificam a cor de formas diferentes por empresa:
     * cliente segue o model number (AGN726-D4 → -D3/-D2),
     * fornecedor usa sufixo -4K (ESL009-26W-4K → -3K/-27K).
     *
     * @param  array{model_suffix: string, supplier_suffix: string}  $target
     */
    private function transformExternalCode(?string $code, array $target): ?string
    {
        if ($code === null) {
            return null;
        }

        $code = preg_replace('/-D4$/', '-'.$target['model_suffix'], $code);

        return preg_replace('/-4K$/i', '-'.$target['supplier_suffix'], $code);
    }
}
