<?php

return [
    'trip_expense' => [
        'title' => 'Travel Expense Report',
        'issued_at' => 'Issued on',
        'trip' => 'Trip',
        'company' => 'Company',
        'destination' => 'Destination',
        'traveler' => 'Traveler',
        'period' => 'Period',
        'fx_rates' => 'Exchange rates',
        'col_datetime' => 'Date/Time',
        'col_category' => 'Category',
        'col_description' => 'Description',
        'col_original' => 'Original amount',
        'col_amount' => 'Amount',
        'col_receipt' => 'Receipt',
        'no_expenses' => 'No expenses.',
        'subtotal' => 'Subtotal',
        'total_to_charge' => 'Total to charge',
        'footer' => 'Amounts converted at the indicative exchange rate provided. Document automatically generated by :company.',
    ],
];
