<?php

namespace App\Filament\Resources\Quotations\Schemas;

use App\Domain\CRM\Models\Company;
use App\Domain\CRM\Models\Contact;
use App\Domain\Quotations\Enums\CommissionType;
use App\Domain\Quotations\Enums\QuotationStatus;
use App\Domain\Settings\Models\Currency;
use App\Domain\Settings\Models\PaymentTerm;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Components\Tabs;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Components\Utilities\Set;
use Filament\Schemas\Schema;

class QuotationForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Tabs::make('Quotation')
                    ->tabs([
                        Tabs\Tab::make(__('forms.tabs.general'))
                            ->icon('heroicon-o-information-circle')
                            ->schema(static::generalTab()),
                        Tabs\Tab::make(__('forms.tabs.commercial'))
                            ->icon('heroicon-o-currency-dollar')
                            ->schema(static::commercialTab()),
                        Tabs\Tab::make(__('forms.tabs.notes'))
                            ->icon('heroicon-o-chat-bubble-left-right')
                            ->schema(static::notesTab()),
                    ])
                    ->columnSpanFull()
                    ->persistTabInQueryString(),
            ]);
    }

    protected static function generalTab(): array
    {
        return [
            Section::make(__('forms.sections.quotation_identity'))
                ->schema([
                    TextInput::make('reference')
                        ->label(__('forms.labels.reference'))
                        ->disabled()
                        ->dehydrated()
                        ->helperText(__('forms.helpers.autogenerated_on_creation'))
                        ->placeholder(__('forms.placeholders.qt2026xxxx')),
                    Select::make('status')
                        ->label(__('forms.labels.status'))
                        ->options(QuotationStatus::class)
                        ->required()
                        ->default(QuotationStatus::DRAFT->value)
                        ->disabled(fn (?\Illuminate\Database\Eloquent\Model $record) => $record !== null)
                        ->dehydrated(),
                ])
                ->columns(2),

            Section::make(__('forms.sections.client'))
                ->schema([
                    Select::make('company_id')
                        ->label(__('forms.labels.company'))
                        ->options(
                            fn () => Company::query()
                                ->whereHas('companyRoles', fn ($q) => $q->where('role', \App\Domain\CRM\Enums\CompanyRole::CLIENT))
                                ->orderBy('name')
                                ->pluck('name', 'id')
                        )
                        ->searchable()
                        ->required()
                        ->live()
                        ->afterStateUpdated(fn (Set $set) => $set('contact_id', null)),
                    Select::make('contact_id')
                        ->label(__('forms.labels.contact'))
                        ->options(function (Get $get) {
                            $companyId = $get('company_id');
                            if (! $companyId) {
                                return [];
                            }

                            return Contact::where('company_id', $companyId)
                                ->orderBy('name')
                                ->pluck('name', 'id');
                        })
                        ->searchable()
                        ->helperText(__('forms.helpers.select_the_client_contact_for_this_quotation')),
                ])
                ->columns(2),
        ];
    }

    protected static function commercialTab(): array
    {
        return [
            Section::make(__('forms.sections.pricing_commission'))
                ->schema([
                    Select::make('currency_code')
                        ->label(__('forms.labels.currency'))
                        ->options(fn () => Currency::where('is_active', true)->pluck('code', 'code'))
                        ->searchable()
                        ->required()
                        ->default('USD'),
                    Select::make('commission_type')
                        ->label(__('forms.labels.commission_model'))
                        ->options(CommissionType::class)
                        ->required()
                        ->default(CommissionType::EMBEDDED->value)
                        ->live()
                        ->helperText(__('forms.helpers.embedded_commission_per_item_separate_commission_on_total')),
                    TextInput::make('commission_rate')
                        ->label(__('forms.labels.commission_rate_2'))
                        ->numeric()
                        ->minValue(0)
                        ->maxValue(100)
                        ->step(0.01)
                        ->suffix('%')
                        ->default(0)
                        ->visible(fn (Get $get) => $get('commission_type') === CommissionType::SEPARATE->value || $get('commission_type') === CommissionType::SEPARATE)
                        ->helperText(__('forms.helpers.applied_to_the_total_value_separate_model_only')),
                    Toggle::make('show_suppliers')
                        ->label(__('forms.labels.show_suppliers_to_client'))
                        ->default(false)
                        ->helperText(__('forms.helpers.if_enabled_supplier_names_will_appear_in_the_client_pdf')),
                ])
                ->columns(2),

            Section::make(__('forms.sections.terms_validity'))
                ->schema([
                    Select::make('payment_term_id')
                        ->label(__('forms.labels.payment_terms'))
                        ->options(fn () => PaymentTerm::where('is_active', true)->pluck('name', 'id'))
                        ->searchable()
                        ->preload(),
                    TextInput::make('validity_days')
                        ->label(__('forms.labels.validity_days'))
                        ->numeric()
                        ->minValue(1)
                        ->default(30)
                        ->live(onBlur: true)
                        ->afterStateUpdated(function (Set $set, ?string $state) {
                            if ($state && is_numeric($state)) {
                                $set('valid_until', now()->addDays((int) $state)->format('Y-m-d'));
                            }
                        }),
                    DatePicker::make('valid_until')
                        ->label(__('forms.labels.valid_until'))
                        ->native(false)
                        ->displayFormat('d/m/Y'),
                ])
                ->columns(3),
        ];
    }

    protected static function notesTab(): array
    {
        return [
            Section::make(__('forms.sections.notes'))
                ->schema([
                    Textarea::make('notes')
                        ->label(__('forms.labels.client_notes'))
                        ->rows(4)
                        ->maxLength(5000)
                        ->helperText(__('forms.helpers.visible_to_the_client_in_the_pdf'))
                        ->columnSpanFull(),
                    Textarea::make('internal_notes')
                        ->label(__('forms.labels.internal_notes'))
                        ->rows(4)
                        ->maxLength(5000)
                        ->helperText(__('forms.helpers.only_visible_internally_never_shown_to_client'))
                        ->columnSpanFull(),
                ]),
        ];
    }
}
