<?php

namespace App\Filament\Resources\Catalog\Categories\Schemas;

use App\Domain\Catalog\Models\Category;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Components\Utilities\Set;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Illuminate\Support\Str;

class CategoryForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make(__('forms.sections.category_details'))
                    ->schema([
                        TextInput::make('name')
                            ->label(__('forms.labels.name'))
                            ->required()
                            ->maxLength(255)
                            ->live(onBlur: true)
                            ->afterStateUpdated(fn (Set $set, ?string $state) => $set('slug', Str::slug($state))),
                        TextInput::make('slug')
                            ->label(__('forms.labels.slug'))
                            ->required()
                            ->maxLength(255)
                            ->unique(ignoreRecord: true)
                            ->helperText(__('forms.helpers.autogenerated_from_name_used_in_urls')),
                        TextInput::make('sku_prefix')
                            ->label(__('forms.labels.sku_prefix'))
                            ->maxLength(10)
                            ->unique(ignoreRecord: true)
                            ->placeholder(__('forms.placeholders.ele'))
                            ->helperText(__('forms.helpers.used_as_prefix_for_product_skus_in_this_category_eg_ele')),
                        Select::make('parent_id')
                            ->label(__('forms.labels.parent_category'))
                            ->options(function (?Category $record) {
                                return Category::query()
                                    ->when($record, fn ($q) => $q->where('id', '!=', $record->id))
                                    ->orderBy('name')
                                    ->get()
                                    ->mapWithKeys(fn (Category $cat) => [$cat->id => $cat->full_path]);
                            })
                            ->searchable()
                            ->placeholder(__('forms.placeholders.none_root_category')),
                        TextInput::make('sort_order')
                            ->label(__('forms.labels.sort_order'))
                            ->numeric()
                            ->default(0)
                            ->minValue(0),
                        Toggle::make('is_active')
                            ->label(__('forms.labels.active'))
                            ->default(true),
                        Textarea::make('description')
                            ->label(__('forms.labels.description'))
                            ->rows(3)
                            ->maxLength(1000)
                            ->columnSpanFull(),
                    ])
                    ->columns(2),
            ]);
    }
}
