<?php

namespace App\Filament\Resources\ProformaInvoices\Schemas;

use App\Domain\CRM\Enums\CompanyRole;
use App\Domain\CRM\Models\Company;
use App\Domain\CRM\Models\Contact;
use App\Domain\Inquiries\Models\Inquiry;
use App\Domain\ProformaInvoices\Enums\ConfirmationMethod;
use App\Domain\ProformaInvoices\Enums\ProformaInvoiceStatus;
use App\Domain\Quotations\Enums\Incoterm;
use App\Domain\Settings\Models\Currency;
use App\Domain\Settings\Models\PaymentTerm;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\DateTimePicker;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Components\Tabs;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Components\Utilities\Set;
use Filament\Schemas\Schema;

class ProformaInvoiceForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Tabs::make('ProformaInvoice')
                    ->tabs([
                        Tabs\Tab::make(__('forms.tabs.general'))
                            ->icon('heroicon-o-information-circle')
                            ->schema(static::generalTab()),
                        Tabs\Tab::make(__('forms.tabs.commercial'))
                            ->icon('heroicon-o-currency-dollar')
                            ->schema(static::commercialTab()),
                        Tabs\Tab::make(__('forms.tabs.confirmation'))
                            ->icon('heroicon-o-check-badge')
                            ->schema(static::confirmationTab()),
                        Tabs\Tab::make(__('forms.tabs.notes'))
                            ->icon('heroicon-o-chat-bubble-left-right')
                            ->schema(static::notesTab()),
                    ])
                    ->columnSpanFull()
                    ->persistTabInQueryString(),
            ]);
    }

    protected static function generalTab(): array
    {
        return [
            Section::make(__('forms.sections.invoice_identity'))
                ->schema([
                    TextInput::make('reference')
                        ->label(__('forms.labels.reference'))
                        ->disabled()
                        ->dehydrated()
                        ->helperText(__('forms.helpers.autogenerated_on_creation'))
                        ->placeholder(__('forms.placeholders.pi2026xxxxx')),
                    Select::make('status')
                        ->label(__('forms.labels.status'))
                        ->options(ProformaInvoiceStatus::class)
                        ->required()
                        ->default(ProformaInvoiceStatus::DRAFT->value)
                        ->disabled(fn (?\Illuminate\Database\Eloquent\Model $record) => $record !== null)
                        ->dehydrated(),
                    Select::make('inquiry_id')
                        ->label(__('forms.labels.inquiry'))
                        ->options(
                            fn () => Inquiry::query()
                                ->orderByDesc('id')
                                ->limit(100)
                                ->get()
                                ->mapWithKeys(fn ($i) => [
                                    $i->id => $i->reference . ' — ' . ($i->company?->name ?? 'N/A'),
                                ])
                        )
                        ->searchable()
                        ->required()
                        ->live()
                        ->afterStateUpdated(function (Set $set, ?string $state) {
                            if ($state) {
                                $inquiry = Inquiry::find($state);
                                if ($inquiry) {
                                    $set('company_id', $inquiry->company_id);
                                    $set('contact_id', $inquiry->contact_id);
                                    $set('currency_code', $inquiry->currency_code ?? 'USD');
                                }
                            }
                        })
                        ->helperText(__('forms.helpers.the_client_inquiry_this_proforma_invoice_is_for')),
                    Select::make('currency_code')
                        ->label(__('forms.labels.currency'))
                        ->options(fn () => Currency::where('is_active', true)->pluck('code', 'code'))
                        ->searchable()
                        ->required()
                        ->default('USD'),
                ])
                ->columns(2),

            Section::make(__('forms.sections.client'))
                ->schema([
                    Select::make('company_id')
                        ->label(__('forms.labels.client'))
                        ->options(
                            fn () => Company::query()
                                ->whereHas('companyRoles', fn ($q) => $q->where('role', CompanyRole::CLIENT))
                                ->orderBy('name')
                                ->pluck('name', 'id')
                        )
                        ->searchable()
                        ->required()
                        ->live()
                        ->afterStateUpdated(fn (Set $set) => $set('contact_id', null)),
                    Select::make('contact_id')
                        ->label(__('forms.labels.contact'))
                        ->options(function (Get $get) {
                            $companyId = $get('company_id');
                            if (! $companyId) {
                                return [];
                            }

                            return Contact::where('company_id', $companyId)
                                ->orderBy('name')
                                ->pluck('name', 'id');
                        })
                        ->searchable()
                        ->helperText(__('forms.helpers.client_contact_person')),
                ])
                ->columns(2),

            Section::make(__('forms.sections.dates'))
                ->schema([
                    DatePicker::make('issue_date')
                        ->label(__('forms.labels.issue_date'))
                        ->native(false)
                        ->displayFormat('d/m/Y')
                        ->default(now())
                        ->required(),
                    TextInput::make('validity_days')
                        ->label(__('forms.labels.validity_days'))
                        ->numeric()
                        ->minValue(1)
                        ->default(30)
                        ->live(onBlur: true)
                        ->afterStateUpdated(function (Set $set, ?string $state) {
                            if ($state && is_numeric($state)) {
                                $set('valid_until', now()->addDays((int) $state)->format('Y-m-d'));
                            }
                        }),
                    DatePicker::make('valid_until')
                        ->label(__('forms.labels.valid_until'))
                        ->native(false)
                        ->displayFormat('d/m/Y'),
                ])
                ->columns(3),
        ];
    }

    protected static function commercialTab(): array
    {
        return [
            Section::make(__('forms.sections.commercial_terms'))
                ->schema([
                    Select::make('incoterm')
                        ->label(__('forms.labels.incoterm'))
                        ->options(Incoterm::class)
                        ->searchable(),
                    Select::make('payment_term_id')
                        ->label(__('forms.labels.payment_terms'))
                        ->options(fn () => PaymentTerm::where('is_active', true)->pluck('name', 'id'))
                        ->searchable()
                        ->preload(),
                ])
                ->columns(2),
        ];
    }

    protected static function confirmationTab(): array
    {
        return [
            Section::make(__('forms.sections.client_confirmation'))
                ->schema([
                    Select::make('confirmation_method')
                        ->label(__('forms.labels.confirmation_method'))
                        ->options(ConfirmationMethod::class)
                        ->helperText(__('forms.helpers.how_the_client_confirmed_this_proforma_invoice')),
                    TextInput::make('confirmation_reference')
                        ->label(__('forms.labels.confirmation_reference'))
                        ->maxLength(255)
                        ->helperText(__('forms.helpers.email_subject_message_id_document_number_etc')),
                    DateTimePicker::make('confirmed_at')
                        ->label(__('forms.labels.confirmed_at'))
                        ->native(false)
                        ->displayFormat('d/m/Y H:i')
                        ->helperText(__('forms.helpers.date_and_time_the_client_confirmed')),
                ])
                ->columns(3)
                ->description(__('forms.descriptions.record_how_and_when_the_client_confirmed_this_proforma')),
        ];
    }

    protected static function notesTab(): array
    {
        return [
            Section::make(__('forms.sections.notes'))
                ->schema([
                    Textarea::make('notes')
                        ->label(__('forms.labels.client_notes'))
                        ->rows(4)
                        ->maxLength(5000)
                        ->helperText(__('forms.helpers.visible_to_the_client_in_the_pdf'))
                        ->columnSpanFull(),
                    Textarea::make('internal_notes')
                        ->label(__('forms.labels.internal_notes'))
                        ->rows(4)
                        ->maxLength(5000)
                        ->helperText(__('forms.helpers.only_visible_internally_never_shown_to_client'))
                        ->columnSpanFull(),
                ]),
        ];
    }
}
