<?php

namespace App\Filament\Resources\Inquiries\Schemas;

use App\Domain\CRM\Models\Company;
use App\Domain\CRM\Models\Contact;
use App\Domain\Inquiries\Enums\InquirySource;
use App\Domain\Inquiries\Enums\InquiryStatus;
use App\Domain\Settings\Models\Currency;
use App\Domain\Users\Enums\UserType;
use App\Models\User;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Components\Tabs;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Components\Utilities\Set;
use Filament\Schemas\Schema;

class InquiryForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Tabs::make('Inquiry')
                    ->tabs([
                        Tabs\Tab::make(__('forms.tabs.general'))
                            ->icon('heroicon-o-information-circle')
                            ->schema(static::generalTab()),
                        Tabs\Tab::make(__('forms.tabs.notes'))
                            ->icon('heroicon-o-chat-bubble-left-right')
                            ->schema(static::notesTab()),
                    ])
                    ->columnSpanFull()
                    ->persistTabInQueryString(),
            ]);
    }

    protected static function generalTab(): array
    {
        return [
            Section::make(__('forms.sections.inquiry_identity'))
                ->schema([
                    TextInput::make('reference')
                        ->label(__('forms.labels.reference'))
                        ->disabled()
                        ->dehydrated()
                        ->helperText(__('forms.helpers.autogenerated_on_creation'))
                        ->placeholder(__('forms.placeholders.inq2026xxxxx')),
                    Select::make('status')
                        ->label(__('forms.labels.status'))
                        ->options(InquiryStatus::class)
                        ->required()
                        ->default(InquiryStatus::RECEIVED->value)
                        ->disabled(fn (?\Illuminate\Database\Eloquent\Model $record) => $record !== null)
                        ->dehydrated(),
                    Select::make('source')
                        ->label(__('forms.labels.source'))
                        ->options(InquirySource::class)
                        ->required()
                        ->default(InquirySource::EMAIL->value),
                    Select::make('currency_code')
                        ->label(__('forms.labels.currency'))
                        ->options(fn () => Currency::where('is_active', true)->pluck('code', 'code'))
                        ->searchable()
                        ->required()
                        ->default('USD'),
                    Select::make('responsible_user_id')
                        ->label(__('forms.labels.responsible'))
                        ->options(
                            fn () => User::where('type', UserType::INTERNAL)
                                ->orderBy('name')
                                ->pluck('name', 'id')
                        )
                        ->searchable()
                        ->default(fn () => auth()->id())
                        ->helperText(__('forms.helpers.person_responsible_for_this_inquiry')),
                ])
                ->columns(2),

            Section::make(__('forms.sections.client'))
                ->schema([
                    Select::make('company_id')
                        ->label(__('forms.labels.company'))
                        ->options(
                            fn () => Company::query()
                                ->whereHas('companyRoles', fn ($q) => $q->where('role', \App\Domain\CRM\Enums\CompanyRole::CLIENT))
                                ->orderBy('name')
                                ->pluck('name', 'id')
                        )
                        ->searchable()
                        ->required()
                        ->live()
                        ->afterStateUpdated(fn (Set $set) => $set('contact_id', null)),
                    Select::make('contact_id')
                        ->label(__('forms.labels.contact'))
                        ->options(function (Get $get) {
                            $companyId = $get('company_id');
                            if (! $companyId) {
                                return [];
                            }

                            return Contact::where('company_id', $companyId)
                                ->orderBy('name')
                                ->pluck('name', 'id');
                        })
                        ->searchable()
                        ->helperText(__('forms.helpers.select_the_client_contact_for_this_inquiry')),
                ])
                ->columns(2),

            Section::make(__('forms.sections.dates'))
                ->schema([
                    DatePicker::make('received_at')
                        ->label(__('forms.labels.received_date'))
                        ->native(false)
                        ->displayFormat('d/m/Y')
                        ->default(now())
                        ->required(),
                    DatePicker::make('deadline')
                        ->label(__('forms.labels.response_deadline'))
                        ->native(false)
                        ->displayFormat('d/m/Y')
                        ->helperText(__('forms.helpers.client_deadline_for_receiving_the_quotation')),
                ])
                ->columns(2),
        ];
    }

    protected static function notesTab(): array
    {
        return [
            Section::make(__('forms.sections.notes'))
                ->schema([
                    Textarea::make('notes')
                        ->label(__('forms.labels.client_notes_requirements'))
                        ->rows(5)
                        ->maxLength(5000)
                        ->helperText(__('forms.helpers.original_client_request_details_requirements_or_special'))
                        ->columnSpanFull(),
                    Textarea::make('internal_notes')
                        ->label(__('forms.labels.internal_notes'))
                        ->rows(4)
                        ->maxLength(5000)
                        ->helperText(__('forms.helpers.internal_observations_strategy_notes_etc'))
                        ->columnSpanFull(),
                ]),
        ];
    }
}
