<?php

namespace App\Filament\Resources\SupplierQuotations\Schemas;

use App\Domain\CRM\Enums\CompanyRole;
use App\Domain\CRM\Models\Company;
use App\Domain\CRM\Models\Contact;
use App\Domain\Inquiries\Models\Inquiry;
use App\Domain\Quotations\Enums\Incoterm;
use App\Domain\Settings\Enums\CalculationBase;
use App\Domain\Settings\Models\Currency;
use App\Domain\Settings\Models\PaymentTerm;
use App\Domain\Users\Enums\UserType;
use App\Models\User;
use Filament\Forms\Components\Repeater;
use Filament\Forms\Components\TextInput as FormTextInput;
use Filament\Forms\Components\Toggle;
use App\Domain\SupplierQuotations\Enums\SupplierQuotationStatus;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\Select;
use Filament\Schemas\Components\Tabs;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Components\Utilities\Set;
use Filament\Schemas\Schema;

class SupplierQuotationForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Tabs::make('SupplierQuotation')
                    ->tabs([
                        Tabs\Tab::make(__('forms.tabs.general'))
                            ->icon('heroicon-o-information-circle')
                            ->schema(static::generalTab()),
                        Tabs\Tab::make(__('forms.tabs.commercial'))
                            ->icon('heroicon-o-currency-dollar')
                            ->schema(static::commercialTab()),
                        Tabs\Tab::make(__('forms.tabs.notes'))
                            ->icon('heroicon-o-chat-bubble-left-right')
                            ->schema(static::notesTab()),
                    ])
                    ->columnSpanFull()
                    ->persistTabInQueryString(),
            ]);
    }

    protected static function generalTab(): array
    {
        return [
            Section::make(__('forms.sections.quotation_identity'))
                ->schema([
                    TextInput::make('reference')
                        ->label(__('forms.labels.reference'))
                        ->disabled()
                        ->dehydrated()
                        ->helperText(__('forms.helpers.autogenerated_on_creation'))
                        ->placeholder(__('forms.placeholders.sq2026xxxxx')),
                    Select::make('status')
                        ->label(__('forms.labels.status'))
                        ->options(SupplierQuotationStatus::class)
                        ->required()
                        ->default(SupplierQuotationStatus::REQUESTED->value)
                        ->disabled(fn (?\Illuminate\Database\Eloquent\Model $record) => $record !== null)
                        ->dehydrated(),
                    Select::make('inquiry_id')
                        ->label(__('forms.labels.inquiry'))
                        ->options(
                            fn () => Inquiry::query()
                                ->orderByDesc('id')
                                ->limit(100)
                                ->get()
                                ->mapWithKeys(fn ($i) => [
                                    $i->id => $i->reference . ' — ' . ($i->company?->name ?? 'N/A'),
                                ])
                        )
                        ->searchable()
                        ->required()
                        ->helperText(__('forms.helpers.the_client_inquiry_this_supplier_quotation_is_for')),
                    Select::make('currency_code')
                        ->label(__('forms.labels.currency'))
                        ->options(fn () => Currency::where('is_active', true)->pluck('code', 'code'))
                        ->searchable()
                        ->required()
                        ->default('USD'),
                    Select::make('responsible_user_id')
                        ->label(__('forms.labels.responsible'))
                        ->options(
                            fn () => User::where('type', UserType::INTERNAL)
                                ->orderBy('name')
                                ->pluck('name', 'id')
                        )
                        ->searchable()
                        ->default(fn () => auth()->id()),
                ])
                ->columns(2),

            Section::make(__('forms.sections.supplier'))
                ->schema([
                    Select::make('company_id')
                        ->label(__('forms.labels.supplier'))
                        ->options(
                            fn () => Company::query()
                                ->whereHas('companyRoles', fn ($q) => $q->where('role', CompanyRole::SUPPLIER))
                                ->orderBy('name')
                                ->pluck('name', 'id')
                        )
                        ->searchable()
                        ->required()
                        ->live()
                        ->afterStateUpdated(fn (Set $set) => $set('contact_id', null)),
                    Select::make('contact_id')
                        ->label(__('forms.labels.contact'))
                        ->options(function (Get $get) {
                            $companyId = $get('company_id');
                            if (! $companyId) {
                                return [];
                            }

                            return Contact::where('company_id', $companyId)
                                ->orderBy('name')
                                ->pluck('name', 'id');
                        })
                        ->searchable()
                        ->helperText(__('forms.helpers.supplier_contact_person')),
                    TextInput::make('supplier_reference')
                        ->label(__('forms.labels.supplier_quotation_number'))
                        ->maxLength(100)
                        ->helperText('The supplier\'s own reference/quotation number.')
                        ->columnSpanFull(),
                ])
                ->columns(2),

            Section::make(__('forms.sections.dates'))
                ->schema([
                    DatePicker::make('requested_at')
                        ->label(__('forms.labels.requested_date'))
                        ->native(false)
                        ->displayFormat('d/m/Y')
                        ->default(now())
                        ->required(),
                    DatePicker::make('received_at')
                        ->label(__('forms.labels.received_date'))
                        ->native(false)
                        ->displayFormat('d/m/Y')
                        ->helperText(__('forms.helpers.date_the_supplier_sent_the_quotation')),
                    DatePicker::make('valid_until')
                        ->label(__('forms.labels.valid_until'))
                        ->native(false)
                        ->displayFormat('d/m/Y')
                        ->helperText(__('forms.helpers.supplier_quotation_expiration_date')),
                ])
                ->columns(3),
        ];
    }

    protected static function commercialTab(): array
    {
        return [
            Section::make(__('forms.sections.commercial_terms'))
                ->schema([
                    TextInput::make('lead_time_days')
                        ->label(__('forms.labels.lead_time_days'))
                        ->numeric()
                        ->minValue(0)
                        ->helperText(__('forms.helpers.overall_lead_time_in_days_from_order_to_delivery')),
                    TextInput::make('moq')
                        ->label(__('forms.labels.moq'))
                        ->numeric()
                        ->minValue(0)
                        ->helperText(__('forms.helpers.minimum_order_quantity_for_this_quotation')),
                    Select::make('incoterm')
                        ->label(__('forms.labels.incoterm'))
                        ->options(Incoterm::class)
                        ->searchable(),
                    Select::make('payment_term_id')
                        ->label(__('forms.labels.payment_terms'))
                        ->relationship('paymentTerm', 'name')
                        ->options(fn () => PaymentTerm::active()->orderBy('name')->pluck('name', 'id'))
                        ->searchable()
                        ->preload()
                        ->createOptionForm([
                            TextInput::make('name')
                                ->label(__('forms.labels.name'))
                                ->required()
                                ->maxLength(255)
                                ->placeholder(__('forms.placeholders.eg_3070_30_deposit_70_before_shipment'))
                                ->columnSpanFull(),
                            Textarea::make('description')
                                ->label(__('forms.labels.description'))
                                ->rows(2)
                                ->maxLength(65535)
                                ->columnSpanFull(),
                            Toggle::make('is_active')
                                ->label(__('forms.labels.active'))
                                ->default(true),
                            Repeater::make('stages')
                                ->relationship()
                                ->schema([
                                    FormTextInput::make('percentage')
                                        ->label(__('forms.labels.percentage'))
                                        ->required()
                                        ->numeric()
                                        ->suffix('%')
                                        ->minValue(1)
                                        ->maxValue(100),
                                    FormTextInput::make('days')
                                        ->label(__('forms.labels.days'))
                                        ->required()
                                        ->numeric()
                                        ->default(0)
                                        ->minValue(0),
                                    Select::make('calculation_base')
                                        ->label(__('forms.labels.calculation_base'))
                                        ->options(CalculationBase::class)
                                        ->required()
                                        ->default(CalculationBase::ORDER_DATE->value),
                                ])
                                ->columns(3)
                                ->orderColumn('sort_order')
                                ->reorderable()
                                ->addActionLabel('Add Stage')
                                ->defaultItems(1)
                                ->minItems(1)
                                ->columnSpanFull(),
                        ])
                        ->createOptionModalHeading('Create Payment Term')
                        ->helperText(__('forms.helpers.select_or_create_a_new_payment_term'))
                        ->columnSpanFull(),
                ])
                ->columns(3),
        ];
    }

    protected static function notesTab(): array
    {
        return [
            Section::make(__('forms.sections.notes'))
                ->schema([
                    Textarea::make('notes')
                        ->label(__('forms.labels.supplier_notes'))
                        ->rows(5)
                        ->maxLength(5000)
                        ->helperText(__('forms.helpers.notes_from_the_supplier_conditions_remarks'))
                        ->columnSpanFull(),
                    Textarea::make('internal_notes')
                        ->label(__('forms.labels.internal_notes'))
                        ->rows(4)
                        ->maxLength(5000)
                        ->helperText(__('forms.helpers.internal_analysis_observations_comparison_notes'))
                        ->columnSpanFull(),
                    Textarea::make('rfq_instructions')
                        ->label(__('forms.labels.rfq_instructions'))
                        ->rows(4)
                        ->maxLength(5000)
                        ->helperText(__('forms.helpers.custom_instructions_for_this_rfq_leave_empty_to_use_the'))
                        ->columnSpanFull(),
                ]),
        ];
    }
}
