<?php

namespace App\Filament\Resources\PurchaseOrders\Schemas;

use App\Domain\CRM\Enums\CompanyRole;
use App\Domain\CRM\Models\Company;
use App\Domain\CRM\Models\Contact;
use App\Domain\ProformaInvoices\Enums\ConfirmationMethod;
use App\Domain\ProformaInvoices\Models\ProformaInvoice;
use App\Domain\PurchaseOrders\Enums\PurchaseOrderStatus;
use App\Domain\Quotations\Enums\Incoterm;
use App\Domain\Settings\Models\Currency;
use App\Domain\Settings\Models\PaymentTerm;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\DateTimePicker;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Components\Tabs;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Components\Utilities\Set;
use Filament\Schemas\Schema;

class PurchaseOrderForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Tabs::make('PurchaseOrder')
                    ->tabs([
                        Tabs\Tab::make(__('forms.tabs.general'))
                            ->icon('heroicon-o-information-circle')
                            ->schema(static::generalTab()),
                        Tabs\Tab::make(__('forms.tabs.commercial'))
                            ->icon('heroicon-o-currency-dollar')
                            ->schema(static::commercialTab()),
                        Tabs\Tab::make(__('forms.tabs.confirmation'))
                            ->icon('heroicon-o-check-badge')
                            ->schema(static::confirmationTab()),
                        Tabs\Tab::make(__('forms.tabs.notes'))
                            ->icon('heroicon-o-chat-bubble-left-right')
                            ->schema(static::notesTab()),
                    ])
                    ->columnSpanFull()
                    ->persistTabInQueryString(),
            ]);
    }

    protected static function generalTab(): array
    {
        return [
            Section::make(__('forms.sections.order_identity'))
                ->schema([
                    TextInput::make('reference')
                        ->label(__('forms.labels.reference'))
                        ->disabled()
                        ->dehydrated()
                        ->helperText(__('forms.helpers.autogenerated_on_creation'))
                        ->placeholder(__('forms.placeholders.po2026xxxxx')),
                    Select::make('status')
                        ->label(__('forms.labels.status'))
                        ->options(PurchaseOrderStatus::class)
                        ->required()
                        ->default(PurchaseOrderStatus::DRAFT->value),
                    Select::make('proforma_invoice_id')
                        ->label(__('forms.labels.proforma_invoice'))
                        ->options(
                            fn () => ProformaInvoice::query()
                                ->orderByDesc('id')
                                ->limit(100)
                                ->get()
                                ->mapWithKeys(fn ($pi) => [
                                    $pi->id => $pi->reference . ' — ' . ($pi->company?->name ?? 'N/A'),
                                ])
                        )
                        ->searchable()
                        ->required()
                        ->helperText(__('forms.helpers.the_proforma_invoice_this_po_originates_from')),
                    Select::make('currency_code')
                        ->label(__('forms.labels.currency'))
                        ->options(fn () => Currency::where('is_active', true)->pluck('code', 'code'))
                        ->searchable()
                        ->required()
                        ->default('USD')
                        ->helperText(__('forms.helpers.can_differ_from_pi_currency_for_supplier_negotiation')),
                ])
                ->columns(2),

            Section::make(__('forms.sections.supplier'))
                ->schema([
                    Select::make('supplier_company_id')
                        ->label(__('forms.labels.supplier'))
                        ->options(
                            fn () => Company::query()
                                ->whereHas('companyRoles', fn ($q) => $q->where('role', CompanyRole::SUPPLIER))
                                ->orderBy('name')
                                ->pluck('name', 'id')
                        )
                        ->searchable()
                        ->required()
                        ->live()
                        ->afterStateUpdated(fn (Set $set) => $set('contact_id', null)),
                    Select::make('contact_id')
                        ->label(__('forms.labels.contact'))
                        ->options(function (Get $get) {
                            $companyId = $get('supplier_company_id');
                            if (! $companyId) {
                                return [];
                            }

                            return Contact::where('company_id', $companyId)
                                ->orderBy('name')
                                ->pluck('name', 'id');
                        })
                        ->searchable()
                        ->helperText(__('forms.helpers.supplier_contact_person')),
                ])
                ->columns(2),

            Section::make(__('forms.sections.dates'))
                ->schema([
                    DatePicker::make('issue_date')
                        ->label(__('forms.labels.issue_date'))
                        ->native(false)
                        ->displayFormat('d/m/Y')
                        ->default(now())
                        ->required(),
                    DatePicker::make('expected_delivery_date')
                        ->label(__('forms.labels.expected_delivery'))
                        ->native(false)
                        ->displayFormat('d/m/Y')
                        ->helperText(__('forms.helpers.when_the_supplier_is_expected_to_deliver')),
                ])
                ->columns(2),
        ];
    }

    protected static function commercialTab(): array
    {
        return [
            Section::make(__('forms.sections.commercial_terms'))
                ->schema([
                    Select::make('incoterm')
                        ->label(__('forms.labels.incoterm'))
                        ->options(Incoterm::class)
                        ->searchable(),
                    Select::make('payment_term_id')
                        ->label(__('forms.labels.payment_terms'))
                        ->options(fn () => PaymentTerm::where('is_active', true)->pluck('name', 'id'))
                        ->searchable()
                        ->preload(),
                ])
                ->columns(2),
        ];
    }

    protected static function confirmationTab(): array
    {
        return [
            Section::make(__('forms.sections.supplier_confirmation'))
                ->schema([
                    Select::make('confirmation_method')
                        ->label(__('forms.labels.confirmation_method'))
                        ->options(ConfirmationMethod::class)
                        ->helperText(__('forms.helpers.how_the_supplier_confirmed_this_purchase_order')),
                    TextInput::make('confirmation_reference')
                        ->label(__('forms.labels.confirmation_reference'))
                        ->maxLength(255)
                        ->helperText(__('forms.helpers.email_subject_message_id_document_number_etc')),
                    DateTimePicker::make('confirmed_at')
                        ->label(__('forms.labels.confirmed_at'))
                        ->native(false)
                        ->displayFormat('d/m/Y H:i')
                        ->helperText(__('forms.helpers.date_and_time_the_supplier_confirmed')),
                ])
                ->columns(3)
                ->description(__('forms.descriptions.record_how_and_when_the_supplier_confirmed_this_purchase')),

            Section::make(__('forms.sections.supplier_invoice'))
                ->schema([
                    TextInput::make('supplier_invoice_number')
                        ->label(__('forms.labels.invoice_number'))
                        ->maxLength(255)
                        ->helperText('The supplier\'s own invoice/reference number.'),
                    DatePicker::make('supplier_invoice_date')
                        ->label(__('forms.labels.invoice_date'))
                        ->native(false)
                        ->displayFormat('d/m/Y'),
                ])
                ->columns(2)
                ->description(__('forms.descriptions.invoice_details_upload_invoice_files_packing_lists_and')),
        ];
    }

    protected static function notesTab(): array
    {
        return [
            Section::make(__('forms.sections.notes'))
                ->schema([
                    Textarea::make('notes')
                        ->label(__('forms.labels.supplier_notes'))
                        ->rows(4)
                        ->maxLength(5000)
                        ->helperText(__('forms.helpers.visible_to_the_supplier_in_the_pdf'))
                        ->columnSpanFull(),
                    Textarea::make('internal_notes')
                        ->label(__('forms.labels.internal_notes'))
                        ->rows(4)
                        ->maxLength(5000)
                        ->helperText(__('forms.helpers.only_visible_internally_never_shown_to_supplier'))
                        ->columnSpanFull(),
                    Textarea::make('shipping_instructions')
                        ->label(__('forms.labels.shipping_instructions'))
                        ->rows(4)
                        ->maxLength(5000)
                        ->helperText(__('forms.helpers.shippingdelivery_instructions_for_the_supplier'))
                        ->columnSpanFull(),
                ]),
        ];
    }
}
