<?php

namespace App\Filament\Resources\Catalog\Products\Schemas;

use App\Domain\Catalog\Enums\ProductStatus;
use App\Domain\Logistics\Enums\PackagingType;
use App\Domain\Infrastructure\Support\Money;
use App\Domain\Catalog\Models\Category;
use App\Domain\Catalog\Actions\GenerateProductSkuAction;
use App\Domain\Catalog\Models\Product;
use App\Domain\Catalog\Models\Tag;
use App\Domain\Settings\Models\Currency;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Components\Utilities\Set;
use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Components\Tabs;
use Filament\Schemas\Schema;

class ProductForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Tabs::make('Product')
                    ->tabs([
                        Tabs\Tab::make(__('forms.tabs.general'))
                            ->icon('heroicon-o-information-circle')
                            ->schema(static::generalTab()),
                        Tabs\Tab::make(__('forms.tabs.specifications'))
                            ->icon('heroicon-o-cog-6-tooth')
                            ->schema(static::specificationsTab()),
                        Tabs\Tab::make(__('forms.tabs.packaging'))
                            ->icon('heroicon-o-archive-box')
                            ->schema(static::packagingTab()),
                        Tabs\Tab::make(__('forms.tabs.costing'))
                            ->icon('heroicon-o-calculator')
                            ->schema(static::costingTab()),
                    ])
                    ->columnSpanFull()
                    ->persistTabInQueryString(),
            ]);
    }

    protected static function generalTab(): array
    {
        return [
            Section::make(__('forms.sections.product_identity'))
                ->schema([
                    Select::make('category_id')
                        ->label(__('forms.labels.category'))
                        ->options(
                            fn () => Category::query()
                                ->active()
                                ->orderBy('name')
                                ->get()
                                ->mapWithKeys(fn (Category $cat) => [$cat->id => $cat->full_path])
                        )
                        ->searchable()
                        ->required()
                        ->live()
                        ->afterStateUpdated(function (Set $set, ?string $state) {
                            if ($state) {
                                // preview() não usa lock — é apenas uma sugestão visual.
                                // O SKU final e único é gerado no evento creating do Model.
                                $set('sku', app(GenerateProductSkuAction::class)->preview((int) $state));
                                $category = Category::find((int) $state);
                                if ($category) {
                                    $set('name', $category->name);
                                }
                            }
                        }),
                    TextInput::make('name')
                        ->label(__('forms.labels.product_name'))
                        ->required()
                        ->maxLength(255)
                        ->helperText(__('forms.helpers.autogenerated_from_category_required_attributes_you_can'))
                        ->placeholder(__('forms.placeholders.will_be_autogenerated_from_attributes')),
                    TextInput::make('sku')
                        ->label(__('forms.labels.sku'))
                        ->unique(ignoreRecord: true)
                        ->maxLength(50)
                        ->helperText(__('forms.helpers.autogenerated_from_category_prefix_you_can_override_manually'))
                        ->placeholder(__('forms.placeholders.will_be_autogenerated_on_save')),
                    Select::make('status')
                        ->label(__('forms.labels.status'))
                        ->options(ProductStatus::class)
                        ->required()
                        ->default(ProductStatus::DRAFT->value),
                    Select::make('parent_id')
                        ->label(__('forms.labels.variant_of'))
                        ->relationship('parent', 'name', fn ($query) => $query->whereNull('parent_id'))
                        ->searchable()
                        ->preload()
                        ->placeholder(__('forms.placeholders.none_base_product'))
                        ->helperText(__('forms.helpers.select_a_parent_product_if_this_is_a_variant')),
                    FileUpload::make('avatar')
                        ->label(__('forms.labels.product_image'))
                        ->image()
                        ->directory('products')
                        ->maxSize(2048)
                        ->columnSpanFull(),
                ])
                ->columns(2),

            Section::make(__('forms.sections.international_trade'))
                ->schema([
                    TextInput::make('hs_code')
                        ->label(__('forms.labels.hs_code'))
                        ->maxLength(20)
                        ->placeholder(__('forms.placeholders.853950'))
                        ->helperText(__('forms.helpers.harmonized_system_code_for_customs_classification')),
                    TextInput::make('origin_country')
                        ->label(__('forms.labels.country_of_origin'))
                        ->maxLength(2)
                        ->placeholder(__('forms.placeholders.cn'))
                        ->helperText(__('forms.helpers.iso_31661_alpha2_code')),
                    TextInput::make('brand')
                        ->label(__('forms.labels.brand'))
                        ->maxLength(255),
                    TextInput::make('model_number')
                        ->label(__('forms.labels.model_number'))
                        ->maxLength(255),
                    TextInput::make('certifications')
                        ->label(__('forms.labels.certifications'))
                        ->maxLength(255)
                        ->placeholder(__('forms.placeholders.ce_fcc_rohs'))
                        ->helperText(__('forms.helpers.commaseparated_list_of_certifications')),
                ])
                ->columns(3)
                ->collapsible(),

            Section::make(__('forms.sections.order_defaults'))
                ->schema([
                    TextInput::make('moq')
                        ->label(__('forms.labels.moq'))
                        ->numeric()
                        ->minValue(1)
                        ->helperText(__('forms.helpers.minimum_order_quantity')),
                    TextInput::make('moq_unit')
                        ->label(__('forms.labels.moq_unit'))
                        ->maxLength(20)
                        ->default('pcs'),
                    TextInput::make('lead_time_days')
                        ->label(__('forms.labels.lead_time_days'))
                        ->numeric()
                        ->minValue(0),
                ])
                ->columns(3)
                ->collapsible(),

            Section::make(__('forms.sections.tags_notes'))
                ->schema([
                    Select::make('tags')
                        ->label(__('forms.labels.tags'))
                        ->multiple()
                        ->relationship('tags', 'name')
                        ->preload()
                        ->searchable()
                        ->createOptionForm([
                            TextInput::make('name')
                                ->required()
                                ->maxLength(255),
                            TextInput::make('slug')
                                ->required()
                                ->maxLength(255),
                        ]),
                    Textarea::make('description')
                        ->label(__('forms.labels.description'))
                        ->rows(3)
                        ->maxLength(5000),
                    Textarea::make('internal_notes')
                        ->label(__('forms.labels.internal_notes'))
                        ->rows(2)
                        ->maxLength(5000),
                ])
                ->collapsible()
                ->collapsed(),
        ];
    }

    protected static function specificationsTab(): array
    {
        return [
            Section::make(__('forms.sections.product_dimensions_weight_unpackaged'))
                ->relationship('specification')
                ->schema([
                    TextInput::make('net_weight')
                        ->label(__('forms.labels.net_weight_kg'))
                        ->numeric()
                        ->step(0.001)
                        ->minValue(0)
                        ->helperText(__('forms.helpers.weight_of_1_piece_unpackaged')),
                    TextInput::make('length')
                        ->label(__('forms.labels.length_cm'))
                        ->numeric()
                        ->step(0.01)
                        ->minValue(0),
                    TextInput::make('width')
                        ->label(__('forms.labels.width_cm'))
                        ->numeric()
                        ->step(0.01)
                        ->minValue(0),
                    TextInput::make('height')
                        ->label(__('forms.labels.height_cm'))
                        ->numeric()
                        ->step(0.01)
                        ->minValue(0),
                ])
                ->columns(3),

            Section::make(__('forms.sections.material_finish'))
                ->relationship('specification')
                ->schema([
                    TextInput::make('material')
                        ->label(__('forms.labels.material'))
                        ->maxLength(255),
                    TextInput::make('color')
                        ->label(__('forms.labels.color'))
                        ->maxLength(255),
                    TextInput::make('finish')
                        ->label(__('forms.labels.finish'))
                        ->maxLength(255),
                    Textarea::make('notes')
                        ->label(__('forms.labels.specification_notes'))
                        ->rows(2)
                        ->maxLength(2000)
                        ->columnSpanFull(),
                ])
                ->columns(3),
        ];
    }

    protected static function packagingTab(): array
    {
        return [
            Section::make(__('forms.sections.packaging_type'))
                ->relationship('packaging')
                ->schema([
                    Select::make('packaging_type')
                        ->label(__('forms.labels.packaging_type'))
                        ->options(PackagingType::class)
                        ->default(PackagingType::CARTON->value)
                        ->helperText(__('forms.helpers.primary_packaging_type_for_this_product')),
                ])
                ->columns(3),

            Section::make(__('forms.sections.inner_box'))
                ->relationship('packaging')
                ->schema([
                    TextInput::make('pcs_per_inner_box')
                        ->label(__('forms.labels.pcs_inner_box'))
                        ->numeric()
                        ->minValue(1),
                    TextInput::make('inner_box_length')
                        ->label(__('forms.labels.length_cm'))
                        ->numeric()
                        ->step(0.01)
                        ->minValue(0),
                    TextInput::make('inner_box_width')
                        ->label(__('forms.labels.width_cm'))
                        ->numeric()
                        ->step(0.01)
                        ->minValue(0),
                    TextInput::make('inner_box_height')
                        ->label(__('forms.labels.height_cm'))
                        ->numeric()
                        ->step(0.01)
                        ->minValue(0),
                    TextInput::make('inner_box_weight')
                        ->label(__('forms.labels.gw_inner_box_kg'))
                        ->numeric()
                        ->step(0.001)
                        ->minValue(0)
                        ->helperText(__('forms.helpers.products_inner_box_weight')),
                ])
                ->columns(5),

            Section::make(__('forms.sections.master_carton'))
                ->relationship('packaging')
                ->schema([
                    TextInput::make('pcs_per_carton')
                        ->label(__('forms.labels.pcs_carton'))
                        ->numeric()
                        ->minValue(1)
                        ->live(onBlur: true)
                        ->afterStateUpdated(function (Set $set, ?string $state, $record) {
                            if (! $state || ! $record) {
                                return;
                            }

                            $product = $record instanceof \App\Domain\Catalog\Models\ProductPackaging
                                ? $record->product
                                : $record;

                            $specNetWeight = $product?->specification?->net_weight;

                            if ($specNetWeight && $specNetWeight > 0) {
                                $set('carton_net_weight', round((float) $specNetWeight * (int) $state, 3));
                            }
                        }),
                    TextInput::make('inner_boxes_per_carton')
                        ->label(__('forms.labels.inner_boxes_carton'))
                        ->numeric()
                        ->minValue(1),
                    TextInput::make('carton_length')
                        ->label(__('forms.labels.length_cm'))
                        ->numeric()
                        ->step(0.01)
                        ->minValue(0)
                        ->live(onBlur: true)
                        ->afterStateUpdated(fn (Get $get, Set $set) => static::calculateCbm($get, $set)),
                    TextInput::make('carton_width')
                        ->label(__('forms.labels.width_cm'))
                        ->numeric()
                        ->step(0.01)
                        ->minValue(0)
                        ->live(onBlur: true)
                        ->afterStateUpdated(fn (Get $get, Set $set) => static::calculateCbm($get, $set)),
                    TextInput::make('carton_height')
                        ->label(__('forms.labels.height_cm'))
                        ->numeric()
                        ->step(0.01)
                        ->minValue(0)
                        ->live(onBlur: true)
                        ->afterStateUpdated(fn (Get $get, Set $set) => static::calculateCbm($get, $set)),
                    TextInput::make('carton_net_weight')
                        ->label(__('forms.labels.nw_carton_kg'))
                        ->numeric()
                        ->step(0.001)
                        ->minValue(0)
                        ->helperText(__('forms.helpers.autocalculated_from_spec_nw_pcscarton_editable_for_override')),
                    TextInput::make('carton_weight')
                        ->label(__('forms.labels.gw_carton_kg'))
                        ->numeric()
                        ->step(0.001)
                        ->minValue(0)
                        ->helperText(__('forms.helpers.total_products_carton_filling')),
                    TextInput::make('carton_cbm')
                        ->label(__('forms.labels.cbm_carton'))
                        ->numeric()
                        ->step(0.000001)
                        ->minValue(0)
                        ->helperText(__('forms.helpers.autocalculated_from_l_w_h_1000000_editable_for_override')),
                ])
                ->columns(4),

            Section::make(__('forms.sections.container_loading'))
                ->relationship('packaging')
                ->schema([
                    TextInput::make('cartons_per_20ft')
                        ->label("Cartons / 20' GP")
                        ->numeric()
                        ->minValue(0),
                    TextInput::make('cartons_per_40ft')
                        ->label("Cartons / 40' GP")
                        ->numeric()
                        ->minValue(0),
                    TextInput::make('cartons_per_40hq')
                        ->label("Cartons / 40' HC")
                        ->numeric()
                        ->minValue(0),
                    Textarea::make('packing_notes')
                        ->label(__('forms.labels.packing_notes'))
                        ->rows(2)
                        ->maxLength(2000)
                        ->columnSpanFull(),
                ])
                ->columns(3),
        ];
    }

    protected static function costingTab(): array
    {
        return [
            Section::make(__('forms.sections.cost_breakdown'))
                ->relationship('costing')
                ->schema([
                    Select::make('currency_id')
                        ->label(__('forms.labels.currency'))
                        ->relationship('currency', 'code')
                        ->searchable()
                        ->preload()
                        ->live()
                        ->helperText(__('forms.helpers.currency_for_all_cost_values_below')),
                    TextInput::make('base_price')
                        ->label(__('forms.labels.base_price'))
                        ->numeric()
                        ->minValue(0)
                        ->step(0.0001)
                        ->prefix(fn (Get $get) => static::getCurrencySymbol($get))
                        ->formatStateUsing(fn ($state) => $state ? number_format(Money::toMajor($state), 4, '.', '') : null)
                        ->dehydrateStateUsing(fn ($state) => $state ? Money::toMinor($state) : null),
                    TextInput::make('bom_material_cost')
                        ->label(__('forms.labels.bom_material_cost'))
                        ->numeric()
                        ->minValue(0)
                        ->step(0.0001)
                        ->prefix(fn (Get $get) => static::getCurrencySymbol($get))
                        ->formatStateUsing(fn ($state) => $state ? number_format(Money::toMajor($state), 4, '.', '') : null)
                        ->dehydrateStateUsing(fn ($state) => $state ? Money::toMinor($state) : null),
                    TextInput::make('direct_labor_cost')
                        ->label(__('forms.labels.direct_labor_cost'))
                        ->numeric()
                        ->minValue(0)
                        ->step(0.0001)
                        ->prefix(fn (Get $get) => static::getCurrencySymbol($get))
                        ->formatStateUsing(fn ($state) => $state ? number_format(Money::toMajor($state), 4, '.', '') : null)
                        ->dehydrateStateUsing(fn ($state) => $state ? Money::toMinor($state) : null),
                    TextInput::make('direct_overhead_cost')
                        ->label(__('forms.labels.direct_overhead_cost'))
                        ->numeric()
                        ->minValue(0)
                        ->step(0.0001)
                        ->prefix(fn (Get $get) => static::getCurrencySymbol($get))
                        ->formatStateUsing(fn ($state) => $state ? number_format(Money::toMajor($state), 4, '.', '') : null)
                        ->dehydrateStateUsing(fn ($state) => $state ? Money::toMinor($state) : null),
                    TextInput::make('total_manufacturing_cost')
                        ->label(__('forms.labels.total_manufacturing_cost'))
                        ->numeric()
                        ->minValue(0)
                        ->step(0.0001)
                        ->prefix(fn (Get $get) => static::getCurrencySymbol($get))
                        ->formatStateUsing(fn ($state) => $state ? number_format(Money::toMajor($state), 4, '.', '') : null)
                        ->dehydrateStateUsing(fn ($state) => $state ? Money::toMinor($state) : null)
                        ->helperText(__('forms.helpers.sum_of_bom_labor_overhead')),
                    TextInput::make('markup_percentage')
                        ->label(__('forms.labels.markup_2'))
                        ->numeric()
                        ->step(0.01)
                        ->minValue(0)
                        ->suffix('%'),
                    TextInput::make('calculated_selling_price')
                        ->label(__('forms.labels.calculated_selling_price'))
                        ->numeric()
                        ->minValue(0)
                        ->step(0.0001)
                        ->prefix(fn (Get $get) => static::getCurrencySymbol($get))
                        ->formatStateUsing(fn ($state) => $state ? number_format(Money::toMajor($state), 4, '.', '') : null)
                        ->dehydrateStateUsing(fn ($state) => $state ? Money::toMinor($state) : null)
                        ->helperText(__('forms.helpers.manufacturing_cost_1_markup')),
                ])
                ->columns(2),
        ];
    }

    protected static function getCurrencySymbol(Get $get): string
    {
        $currencyId = $get('currency_id');

        if (! $currencyId) {
            return '$';
        }

        static $cache = [];

        if (! isset($cache[$currencyId])) {
            $currency = Currency::find($currencyId);
            $cache[$currencyId] = $currency?->symbol ?? $currency?->code ?? '$';
        }

        return $cache[$currencyId];
    }

    protected static function calculateCbm(Get $get, Set $set): void
    {
        $length = (float) $get('carton_length');
        $width = (float) $get('carton_width');
        $height = (float) $get('carton_height');

        if ($length > 0 && $width > 0 && $height > 0) {
            $cbm = ($length * $width * $height) / 1_000_000;
            $set('carton_cbm', round($cbm, 6));
        }
    }
}
